AWSTemplateFormatVersion: "2010-09-09"
Description: Create Stack to create EC2 Instance using Conditions

Parameters:
  EC2KeyName:
    Description: Select Key Pair for EC2 Instances
    Type: AWS::EC2::KeyPair::KeyName
  EnvironmentName:
    Description: Select the Environmet
    Type: String
    Default: DEV
    AllowedValues:
      - PROD
      - UAT
      - DEV

Mappings:
  RegionalAMIMapping:
    us-east-1:
      amiId: ami-026b57f3c383c2eec
    us-east-2:
      amiId: ami-0f924dc71d44d23e2
    ap-south-1:
      amiId: ami-01216e7612243e0ef
  MyInstanceTypeMap:
    PROD:
      instanceType: t2.micro
    UAT:
      instanceType: t2.small
    DEV:
      instanceType: t2.large

Resources:
  LinuxInstances:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [RegionalAMIMapping, !Ref AWS::Region, amiId]
      InstanceType: !FindInMap [MyInstanceTypeMap, !Ref EnvironmentName, instanceType]
      KeyName: !Ref EC2KeyName