AWSTemplateFormatVersion: "2010-09-09"
Description: Teamplate to create EC2 Instances and SG.

Parameters:
  EC2KeyPairName:
    Description: "Select the Key Name from the drop down options"
    Type: AWS::EC2::KeyPair::KeyName
  EC2AvailabilityZone:
    Description: Select the Availability Zones from drop down
    Type: String
    Default: us-east-1a
    AllowedValues:
      - us-east-1a
      - us-east-1b
      - us-east-1c
      - us-east-1d
      - us-east-1e
      - us-east-1f
  EC2InstanceType:
    Description: Select the EC2 Instance type from SSM
    Type: AWS::SSM::Parameter::Value<String>
    
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId:  ami-026b57f3c383c2eec
      InstanceType: !Ref EC2InstanceType
      KeyName: !Ref EC2KeyPairName
      SecurityGroups:
        - default
        - !Ref MySecurityGroup
      AvailabilityZone: !Ref EC2AvailabilityZone
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: SSH Security Group
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: '0.0.0.0/0'
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: '0.0.0.0/0'
  AllocatingEIP:
    Type: AWS::EC2::EIP
    Properties: 
      InstanceId: !Ref MyEC2Instance